USE Interview
CREATE TABLE Employee (
	ID INT NOT NULL IDENTITY, CONSTRAINT PK_Employee_ID PRIMARY KEY CLUSTERED (ID),
	Title NVARCHAR(20) NOT NULL,
	FirstName NVARCHAR(60) NOT NULL,
	Surname NVARCHAR(60) NOT NULL,
	Gender NVARCHAR(1) NOT NULL,
	DateOfBirth DATETIME NOT NULL,
	Email NVARCHAR(120) NOT NULL,
	JobTitle NVARCHAR(120) NOT NULL,
	Salary MONEY NOT NULL
)
